// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvbohyopxdnhuhfefnhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2Ym9oeW9weGRuaHVoZmVmbmhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTM5MDAsImV4cCI6MjA2NDU2OTkwMH0.DdhtdrLuTr1RtuuBKQyX--kTej8Bk5hjsD1-O3p-C4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);